# Generated by Django 5.1.3 on 2024-11-17 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_album_album_added_by_alter_album_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='releaseDate',
            new_name='release_Date',
        ),
    ]
