# Generated by Django 5.1.3 on 2024-11-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='phoneNumber',
            field=models.CharField(max_length=11),
        ),
    ]
